# Bible in a Year Reading Plan
# 365 days covering all 66 books of the Bible

BIBLE_IN_A_YEAR_PLAN = [
    # January - Genesis & Matthew
    {"day": 1, "readings": [{"book": "Genesis", "chapters": "1-3"}, {"book": "Matthew", "chapters": "1"}], "theme": "Creation & The Genealogy of Jesus"},
    {"day": 2, "readings": [{"book": "Genesis", "chapters": "4-6"}, {"book": "Matthew", "chapters": "2"}], "theme": "The Fall & The Birth of Jesus"},
    {"day": 3, "readings": [{"book": "Genesis", "chapters": "7-9"}, {"book": "Matthew", "chapters": "3"}], "theme": "Noah's Ark & John the Baptist"},
    {"day": 4, "readings": [{"book": "Genesis", "chapters": "10-12"}, {"book": "Matthew", "chapters": "4"}], "theme": "Tower of Babel & Jesus Begins Ministry"},
    {"day": 5, "readings": [{"book": "Genesis", "chapters": "13-15"}, {"book": "Matthew", "chapters": "5"}], "theme": "Abram's Journey & Sermon on the Mount"},
    {"day": 6, "readings": [{"book": "Genesis", "chapters": "16-18"}, {"book": "Matthew", "chapters": "6"}], "theme": "Hagar & Ishmael & The Lord's Prayer"},
    {"day": 7, "readings": [{"book": "Genesis", "chapters": "19-21"}, {"book": "Matthew", "chapters": "7"}], "theme": "Sodom & Gomorrah & Judging Others"},
    {"day": 8, "readings": [{"book": "Genesis", "chapters": "22-24"}, {"book": "Matthew", "chapters": "8"}], "theme": "Abraham's Test & Jesus Heals"},
    {"day": 9, "readings": [{"book": "Genesis", "chapters": "25-27"}, {"book": "Matthew", "chapters": "9"}], "theme": "Jacob & Esau & Calling of Matthew"},
    {"day": 10, "readings": [{"book": "Genesis", "chapters": "28-30"}, {"book": "Matthew", "chapters": "10"}], "theme": "Jacob's Ladder & Sending the Twelve"},
    {"day": 11, "readings": [{"book": "Genesis", "chapters": "31-33"}, {"book": "Matthew", "chapters": "11"}], "theme": "Jacob Returns & Jesus and John"},
    {"day": 12, "readings": [{"book": "Genesis", "chapters": "34-36"}, {"book": "Matthew", "chapters": "12"}], "theme": "Dinah & Lord of the Sabbath"},
    {"day": 13, "readings": [{"book": "Genesis", "chapters": "37-39"}, {"book": "Matthew", "chapters": "13"}], "theme": "Joseph's Dreams & Parables"},
    {"day": 14, "readings": [{"book": "Genesis", "chapters": "40-42"}, {"book": "Matthew", "chapters": "14"}], "theme": "Joseph Interprets Dreams & Feeding 5000"},
    {"day": 15, "readings": [{"book": "Genesis", "chapters": "43-45"}, {"book": "Matthew", "chapters": "15"}], "theme": "Joseph Reveals Himself & Clean and Unclean"},
    {"day": 16, "readings": [{"book": "Genesis", "chapters": "46-48"}, {"book": "Matthew", "chapters": "16"}], "theme": "Jacob Goes to Egypt & Peter's Confession"},
    {"day": 17, "readings": [{"book": "Genesis", "chapters": "49-50"}, {"book": "Matthew", "chapters": "17"}], "theme": "Jacob's Blessing & Transfiguration"},
    {"day": 18, "readings": [{"book": "Exodus", "chapters": "1-3"}, {"book": "Matthew", "chapters": "18"}], "theme": "Moses' Birth & Greatest in Kingdom"},
    {"day": 19, "readings": [{"book": "Exodus", "chapters": "4-6"}, {"book": "Matthew", "chapters": "19"}], "theme": "Moses Returns & Divorce and Children"},
    {"day": 20, "readings": [{"book": "Exodus", "chapters": "7-9"}, {"book": "Matthew", "chapters": "20"}], "theme": "Plagues Begin & Workers in Vineyard"},
    {"day": 21, "readings": [{"book": "Exodus", "chapters": "10-12"}, {"book": "Matthew", "chapters": "21"}], "theme": "Passover & Triumphal Entry"},
    {"day": 22, "readings": [{"book": "Exodus", "chapters": "13-15"}, {"book": "Matthew", "chapters": "22"}], "theme": "Red Sea Crossing & Greatest Commandment"},
    {"day": 23, "readings": [{"book": "Exodus", "chapters": "16-18"}, {"book": "Matthew", "chapters": "23"}], "theme": "Manna & Woes to Pharisees"},
    {"day": 24, "readings": [{"book": "Exodus", "chapters": "19-21"}, {"book": "Matthew", "chapters": "24"}], "theme": "Ten Commandments & Signs of End"},
    {"day": 25, "readings": [{"book": "Exodus", "chapters": "22-24"}, {"book": "Matthew", "chapters": "25"}], "theme": "Laws & Parables of Judgment"},
    {"day": 26, "readings": [{"book": "Exodus", "chapters": "25-27"}, {"book": "Matthew", "chapters": "26"}], "theme": "Tabernacle Plans & Last Supper"},
    {"day": 27, "readings": [{"book": "Exodus", "chapters": "28-30"}, {"book": "Matthew", "chapters": "27"}], "theme": "Priestly Garments & Crucifixion"},
    {"day": 28, "readings": [{"book": "Exodus", "chapters": "31-33"}, {"book": "Matthew", "chapters": "28"}], "theme": "Golden Calf & Resurrection"},
    {"day": 29, "readings": [{"book": "Exodus", "chapters": "34-36"}, {"book": "Mark", "chapters": "1"}], "theme": "New Tablets & Jesus Begins Ministry"},
    {"day": 30, "readings": [{"book": "Exodus", "chapters": "37-40"}, {"book": "Mark", "chapters": "2"}], "theme": "Tabernacle Built & Jesus Heals"},
    {"day": 31, "readings": [{"book": "Leviticus", "chapters": "1-4"}, {"book": "Mark", "chapters": "3"}], "theme": "Offerings & Choosing the Twelve"},
    
    # February
    {"day": 32, "readings": [{"book": "Leviticus", "chapters": "5-7"}, {"book": "Mark", "chapters": "4"}], "theme": "Sin Offerings & Parables"},
    {"day": 33, "readings": [{"book": "Leviticus", "chapters": "8-10"}, {"book": "Mark", "chapters": "5"}], "theme": "Priests Consecrated & Miracles"},
    {"day": 34, "readings": [{"book": "Leviticus", "chapters": "11-13"}, {"book": "Mark", "chapters": "6"}], "theme": "Clean and Unclean & Feeding 5000"},
    {"day": 35, "readings": [{"book": "Leviticus", "chapters": "14-16"}, {"book": "Mark", "chapters": "7"}], "theme": "Day of Atonement & Traditions"},
    {"day": 36, "readings": [{"book": "Leviticus", "chapters": "17-19"}, {"book": "Mark", "chapters": "8"}], "theme": "Holiness Laws & Peter's Confession"},
    {"day": 37, "readings": [{"book": "Leviticus", "chapters": "20-22"}, {"book": "Mark", "chapters": "9"}], "theme": "Punishments & Transfiguration"},
    {"day": 38, "readings": [{"book": "Leviticus", "chapters": "23-25"}, {"book": "Mark", "chapters": "10"}], "theme": "Feasts & Rich Young Man"},
    {"day": 39, "readings": [{"book": "Leviticus", "chapters": "26-27"}, {"book": "Mark", "chapters": "11"}], "theme": "Blessings and Curses & Triumphal Entry"},
    {"day": 40, "readings": [{"book": "Numbers", "chapters": "1-3"}, {"book": "Mark", "chapters": "12"}], "theme": "Census & Greatest Commandment"},
    {"day": 41, "readings": [{"book": "Numbers", "chapters": "4-6"}, {"book": "Mark", "chapters": "13"}], "theme": "Levite Duties & Signs of End"},
    {"day": 42, "readings": [{"book": "Numbers", "chapters": "7-9"}, {"book": "Mark", "chapters": "14"}], "theme": "Offerings & Last Supper"},
    {"day": 43, "readings": [{"book": "Numbers", "chapters": "10-12"}, {"book": "Mark", "chapters": "15"}], "theme": "Israel Moves & Crucifixion"},
    {"day": 44, "readings": [{"book": "Numbers", "chapters": "13-15"}, {"book": "Mark", "chapters": "16"}], "theme": "Spies Sent & Resurrection"},
    {"day": 45, "readings": [{"book": "Numbers", "chapters": "16-18"}, {"book": "Luke", "chapters": "1"}], "theme": "Korah's Rebellion & Birth Announcements"},
    {"day": 46, "readings": [{"book": "Numbers", "chapters": "19-21"}, {"book": "Luke", "chapters": "2"}], "theme": "Bronze Serpent & Jesus' Birth"},
    {"day": 47, "readings": [{"book": "Numbers", "chapters": "22-24"}, {"book": "Luke", "chapters": "3"}], "theme": "Balaam & John the Baptist"},
    {"day": 48, "readings": [{"book": "Numbers", "chapters": "25-27"}, {"book": "Luke", "chapters": "4"}], "theme": "Joshua Commissioned & Jesus Rejected"},
    {"day": 49, "readings": [{"book": "Numbers", "chapters": "28-30"}, {"book": "Luke", "chapters": "5"}], "theme": "Offerings & Calling Disciples"},
    {"day": 50, "readings": [{"book": "Numbers", "chapters": "31-33"}, {"book": "Luke", "chapters": "6"}], "theme": "Midianites & Beatitudes"},
    {"day": 51, "readings": [{"book": "Numbers", "chapters": "34-36"}, {"book": "Luke", "chapters": "7"}], "theme": "Boundaries & Faith of Centurion"},
    {"day": 52, "readings": [{"book": "Deuteronomy", "chapters": "1-3"}, {"book": "Luke", "chapters": "8"}], "theme": "Moses Reviews & Parables"},
    {"day": 53, "readings": [{"book": "Deuteronomy", "chapters": "4-6"}, {"book": "Luke", "chapters": "9"}], "theme": "Obedience & Transfiguration"},
    {"day": 54, "readings": [{"book": "Deuteronomy", "chapters": "7-9"}, {"book": "Luke", "chapters": "10"}], "theme": "Chosen People & Good Samaritan"},
    {"day": 55, "readings": [{"book": "Deuteronomy", "chapters": "10-12"}, {"book": "Luke", "chapters": "11"}], "theme": "Circumcise Hearts & Lord's Prayer"},
    {"day": 56, "readings": [{"book": "Deuteronomy", "chapters": "13-15"}, {"book": "Luke", "chapters": "12"}], "theme": "False Prophets & Do Not Worry"},
    {"day": 57, "readings": [{"book": "Deuteronomy", "chapters": "16-18"}, {"book": "Luke", "chapters": "13"}], "theme": "Justice & Narrow Door"},
    {"day": 58, "readings": [{"book": "Deuteronomy", "chapters": "19-21"}, {"book": "Luke", "chapters": "14"}], "theme": "Cities of Refuge & Cost of Discipleship"},
    {"day": 59, "readings": [{"book": "Deuteronomy", "chapters": "22-24"}, {"book": "Luke", "chapters": "15"}], "theme": "Various Laws & Lost Parables"},
    
    # March
    {"day": 60, "readings": [{"book": "Deuteronomy", "chapters": "25-27"}, {"book": "Luke", "chapters": "16"}], "theme": "Blessings & Rich Man and Lazarus"},
    {"day": 61, "readings": [{"book": "Deuteronomy", "chapters": "28-30"}, {"book": "Luke", "chapters": "17"}], "theme": "Curses & Ten Lepers"},
    {"day": 62, "readings": [{"book": "Deuteronomy", "chapters": "31-34"}, {"book": "Luke", "chapters": "18"}], "theme": "Moses' Death & Persistent Widow"},
    {"day": 63, "readings": [{"book": "Joshua", "chapters": "1-3"}, {"book": "Luke", "chapters": "19"}], "theme": "Crossing Jordan & Zacchaeus"},
    {"day": 64, "readings": [{"book": "Joshua", "chapters": "4-6"}, {"book": "Luke", "chapters": "20"}], "theme": "Jericho Falls & Authority Questioned"},
    {"day": 65, "readings": [{"book": "Joshua", "chapters": "7-9"}, {"book": "Luke", "chapters": "21"}], "theme": "Achan's Sin & Signs of End"},
    {"day": 66, "readings": [{"book": "Joshua", "chapters": "10-12"}, {"book": "Luke", "chapters": "22"}], "theme": "Sun Stands Still & Last Supper"},
    {"day": 67, "readings": [{"book": "Joshua", "chapters": "13-15"}, {"book": "Luke", "chapters": "23"}], "theme": "Land Divided & Crucifixion"},
    {"day": 68, "readings": [{"book": "Joshua", "chapters": "16-18"}, {"book": "Luke", "chapters": "24"}], "theme": "Tribal Allotments & Resurrection"},
    {"day": 69, "readings": [{"book": "Joshua", "chapters": "19-21"}, {"book": "John", "chapters": "1"}], "theme": "Cities of Refuge & The Word"},
    {"day": 70, "readings": [{"book": "Joshua", "chapters": "22-24"}, {"book": "John", "chapters": "2"}], "theme": "Joshua's Farewell & Water to Wine"},
    {"day": 71, "readings": [{"book": "Judges", "chapters": "1-3"}, {"book": "John", "chapters": "3"}], "theme": "Judges Begin & Born Again"},
    {"day": 72, "readings": [{"book": "Judges", "chapters": "4-6"}, {"book": "John", "chapters": "4"}], "theme": "Deborah & Woman at Well"},
    {"day": 73, "readings": [{"book": "Judges", "chapters": "7-9"}, {"book": "John", "chapters": "5"}], "theme": "Gideon & Healing at Pool"},
    {"day": 74, "readings": [{"book": "Judges", "chapters": "10-12"}, {"book": "John", "chapters": "6"}], "theme": "Jephthah & Bread of Life"},
    {"day": 75, "readings": [{"book": "Judges", "chapters": "13-15"}, {"book": "John", "chapters": "7"}], "theme": "Samson's Birth & Feast of Tabernacles"},
    {"day": 76, "readings": [{"book": "Judges", "chapters": "16-18"}, {"book": "John", "chapters": "8"}], "theme": "Samson & Delilah & Light of World"},
    {"day": 77, "readings": [{"book": "Judges", "chapters": "19-21"}, {"book": "John", "chapters": "9"}], "theme": "Dark Days & Man Born Blind"},
    {"day": 78, "readings": [{"book": "Ruth", "chapters": "1-4"}, {"book": "John", "chapters": "10"}], "theme": "Ruth's Loyalty & Good Shepherd"},
    {"day": 79, "readings": [{"book": "1 Samuel", "chapters": "1-3"}, {"book": "John", "chapters": "11"}], "theme": "Samuel's Birth & Lazarus Raised"},
    {"day": 80, "readings": [{"book": "1 Samuel", "chapters": "4-6"}, {"book": "John", "chapters": "12"}], "theme": "Ark Captured & Mary Anoints Jesus"},
    {"day": 81, "readings": [{"book": "1 Samuel", "chapters": "7-9"}, {"book": "John", "chapters": "13"}], "theme": "Saul Chosen & Washing Feet"},
    {"day": 82, "readings": [{"book": "1 Samuel", "chapters": "10-12"}, {"book": "John", "chapters": "14"}], "theme": "Saul Anointed & The Way"},
    {"day": 83, "readings": [{"book": "1 Samuel", "chapters": "13-15"}, {"book": "John", "chapters": "15"}], "theme": "Saul's Disobedience & The Vine"},
    {"day": 84, "readings": [{"book": "1 Samuel", "chapters": "16-18"}, {"book": "John", "chapters": "16"}], "theme": "David Anointed & Holy Spirit"},
    {"day": 85, "readings": [{"book": "1 Samuel", "chapters": "19-21"}, {"book": "John", "chapters": "17"}], "theme": "David Flees & Jesus Prays"},
    {"day": 86, "readings": [{"book": "1 Samuel", "chapters": "22-24"}, {"book": "John", "chapters": "18"}], "theme": "David Spares Saul & Arrest"},
    {"day": 87, "readings": [{"book": "1 Samuel", "chapters": "25-27"}, {"book": "John", "chapters": "19"}], "theme": "Abigail & Crucifixion"},
    {"day": 88, "readings": [{"book": "1 Samuel", "chapters": "28-31"}, {"book": "John", "chapters": "20"}], "theme": "Saul's Death & Resurrection"},
    {"day": 89, "readings": [{"book": "2 Samuel", "chapters": "1-3"}, {"book": "John", "chapters": "21"}], "theme": "David Mourns & Peter Restored"},
    {"day": 90, "readings": [{"book": "2 Samuel", "chapters": "4-6"}, {"book": "Acts", "chapters": "1"}], "theme": "Ark to Jerusalem & Ascension"},
    
    # April
    {"day": 91, "readings": [{"book": "2 Samuel", "chapters": "7-9"}, {"book": "Acts", "chapters": "2"}], "theme": "Davidic Covenant & Pentecost"},
    {"day": 92, "readings": [{"book": "2 Samuel", "chapters": "10-12"}, {"book": "Acts", "chapters": "3"}], "theme": "David's Sin & Healing at Gate"},
    {"day": 93, "readings": [{"book": "2 Samuel", "chapters": "13-15"}, {"book": "Acts", "chapters": "4"}], "theme": "Absalom & Bold Witness"},
    {"day": 94, "readings": [{"book": "2 Samuel", "chapters": "16-18"}, {"book": "Acts", "chapters": "5"}], "theme": "Absalom's Death & Ananias"},
    {"day": 95, "readings": [{"book": "2 Samuel", "chapters": "19-21"}, {"book": "Acts", "chapters": "6"}], "theme": "David Returns & Stephen"},
    {"day": 96, "readings": [{"book": "2 Samuel", "chapters": "22-24"}, {"book": "Acts", "chapters": "7"}], "theme": "David's Song & Stephen's Speech"},
    {"day": 97, "readings": [{"book": "1 Kings", "chapters": "1-3"}, {"book": "Acts", "chapters": "8"}], "theme": "Solomon's Wisdom & Philip"},
    {"day": 98, "readings": [{"book": "1 Kings", "chapters": "4-6"}, {"book": "Acts", "chapters": "9"}], "theme": "Temple Plans & Saul Converted"},
    {"day": 99, "readings": [{"book": "1 Kings", "chapters": "7-9"}, {"book": "Acts", "chapters": "10"}], "theme": "Temple Built & Cornelius"},
    {"day": 100, "readings": [{"book": "1 Kings", "chapters": "10-12"}, {"book": "Acts", "chapters": "11"}], "theme": "Queen of Sheba & Church Grows"},
    {"day": 101, "readings": [{"book": "1 Kings", "chapters": "13-15"}, {"book": "Acts", "chapters": "12"}], "theme": "Kingdom Divided & Peter Freed"},
    {"day": 102, "readings": [{"book": "1 Kings", "chapters": "16-18"}, {"book": "Acts", "chapters": "13"}], "theme": "Elijah & Barnabas and Paul"},
    {"day": 103, "readings": [{"book": "1 Kings", "chapters": "19-22"}, {"book": "Acts", "chapters": "14"}], "theme": "Still Small Voice & First Journey"},
    {"day": 104, "readings": [{"book": "2 Kings", "chapters": "1-3"}, {"book": "Acts", "chapters": "15"}], "theme": "Elijah Taken & Jerusalem Council"},
    {"day": 105, "readings": [{"book": "2 Kings", "chapters": "4-6"}, {"book": "Acts", "chapters": "16"}], "theme": "Elisha's Miracles & Lydia"},
    {"day": 106, "readings": [{"book": "2 Kings", "chapters": "7-9"}, {"book": "Acts", "chapters": "17"}], "theme": "Lepers & Athens"},
    {"day": 107, "readings": [{"book": "2 Kings", "chapters": "10-12"}, {"book": "Acts", "chapters": "18"}], "theme": "Jehu & Corinth"},
    {"day": 108, "readings": [{"book": "2 Kings", "chapters": "13-15"}, {"book": "Acts", "chapters": "19"}], "theme": "Kings & Ephesus"},
    {"day": 109, "readings": [{"book": "2 Kings", "chapters": "16-18"}, {"book": "Acts", "chapters": "20"}], "theme": "Hezekiah & Paul's Farewell"},
    {"day": 110, "readings": [{"book": "2 Kings", "chapters": "19-21"}, {"book": "Acts", "chapters": "21"}], "theme": "Sennacherib & Paul Arrested"},
    {"day": 111, "readings": [{"book": "2 Kings", "chapters": "22-25"}, {"book": "Acts", "chapters": "22"}], "theme": "Josiah & Paul's Defense"},
    {"day": 112, "readings": [{"book": "1 Chronicles", "chapters": "1-3"}, {"book": "Acts", "chapters": "23"}], "theme": "Genealogies & Plot Against Paul"},
    {"day": 113, "readings": [{"book": "1 Chronicles", "chapters": "4-6"}, {"book": "Acts", "chapters": "24"}], "theme": "Tribes & Felix"},
    {"day": 114, "readings": [{"book": "1 Chronicles", "chapters": "7-9"}, {"book": "Acts", "chapters": "25"}], "theme": "More Genealogies & Festus"},
    {"day": 115, "readings": [{"book": "1 Chronicles", "chapters": "10-12"}, {"book": "Acts", "chapters": "26"}], "theme": "David's Rise & Agrippa"},
    {"day": 116, "readings": [{"book": "1 Chronicles", "chapters": "13-15"}, {"book": "Acts", "chapters": "27"}], "theme": "Ark Moved & Shipwreck"},
    {"day": 117, "readings": [{"book": "1 Chronicles", "chapters": "16-18"}, {"book": "Acts", "chapters": "28"}], "theme": "Worship & Rome"},
    {"day": 118, "readings": [{"book": "1 Chronicles", "chapters": "19-21"}, {"book": "Romans", "chapters": "1"}], "theme": "Census & Gospel Power"},
    {"day": 119, "readings": [{"book": "1 Chronicles", "chapters": "22-24"}, {"book": "Romans", "chapters": "2"}], "theme": "Temple Prep & God's Judgment"},
    {"day": 120, "readings": [{"book": "1 Chronicles", "chapters": "25-27"}, {"book": "Romans", "chapters": "3"}], "theme": "Musicians & Righteousness"},
    
    # May
    {"day": 121, "readings": [{"book": "1 Chronicles", "chapters": "28-29"}, {"book": "Romans", "chapters": "4"}], "theme": "David's Charge & Abraham's Faith"},
    {"day": 122, "readings": [{"book": "2 Chronicles", "chapters": "1-3"}, {"book": "Romans", "chapters": "5"}], "theme": "Solomon's Reign & Peace with God"},
    {"day": 123, "readings": [{"book": "2 Chronicles", "chapters": "4-6"}, {"book": "Romans", "chapters": "6"}], "theme": "Temple & Dead to Sin"},
    {"day": 124, "readings": [{"book": "2 Chronicles", "chapters": "7-9"}, {"book": "Romans", "chapters": "7"}], "theme": "God's Promise & Law and Sin"},
    {"day": 125, "readings": [{"book": "2 Chronicles", "chapters": "10-12"}, {"book": "Romans", "chapters": "8"}], "theme": "Division & Life in Spirit"},
    {"day": 126, "readings": [{"book": "2 Chronicles", "chapters": "13-15"}, {"book": "Romans", "chapters": "9"}], "theme": "Asa's Reforms & God's Sovereignty"},
    {"day": 127, "readings": [{"book": "2 Chronicles", "chapters": "16-18"}, {"book": "Romans", "chapters": "10"}], "theme": "Kings & Salvation for All"},
    {"day": 128, "readings": [{"book": "2 Chronicles", "chapters": "19-21"}, {"book": "Romans", "chapters": "11"}], "theme": "Jehoshaphat & Israel's Future"},
    {"day": 129, "readings": [{"book": "2 Chronicles", "chapters": "22-24"}, {"book": "Romans", "chapters": "12"}], "theme": "Joash & Living Sacrifice"},
    {"day": 130, "readings": [{"book": "2 Chronicles", "chapters": "25-27"}, {"book": "Romans", "chapters": "13"}], "theme": "Kings & Submission"},
    {"day": 131, "readings": [{"book": "2 Chronicles", "chapters": "28-30"}, {"book": "Romans", "chapters": "14"}], "theme": "Hezekiah & Weak and Strong"},
    {"day": 132, "readings": [{"book": "2 Chronicles", "chapters": "31-33"}, {"book": "Romans", "chapters": "15"}], "theme": "Reforms & Unity"},
    {"day": 133, "readings": [{"book": "2 Chronicles", "chapters": "34-36"}, {"book": "Romans", "chapters": "16"}], "theme": "Josiah & Greetings"},
    {"day": 134, "readings": [{"book": "Ezra", "chapters": "1-3"}, {"book": "1 Corinthians", "chapters": "1"}], "theme": "Return & Divisions"},
    {"day": 135, "readings": [{"book": "Ezra", "chapters": "4-6"}, {"book": "1 Corinthians", "chapters": "2"}], "theme": "Opposition & Wisdom"},
    {"day": 136, "readings": [{"book": "Ezra", "chapters": "7-10"}, {"book": "1 Corinthians", "chapters": "3"}], "theme": "Ezra & Building on Christ"},
    {"day": 137, "readings": [{"book": "Nehemiah", "chapters": "1-3"}, {"book": "1 Corinthians", "chapters": "4"}], "theme": "Rebuilding Walls & Servants"},
    {"day": 138, "readings": [{"book": "Nehemiah", "chapters": "4-6"}, {"book": "1 Corinthians", "chapters": "5"}], "theme": "Opposition & Church Discipline"},
    {"day": 139, "readings": [{"book": "Nehemiah", "chapters": "7-9"}, {"book": "1 Corinthians", "chapters": "6"}], "theme": "Reading Law & Body Temple"},
    {"day": 140, "readings": [{"book": "Nehemiah", "chapters": "10-13"}, {"book": "1 Corinthians", "chapters": "7"}], "theme": "Reforms & Marriage"},
    {"day": 141, "readings": [{"book": "Esther", "chapters": "1-3"}, {"book": "1 Corinthians", "chapters": "8"}], "theme": "Esther Chosen & Food Offered to Idols"},
    {"day": 142, "readings": [{"book": "Esther", "chapters": "4-6"}, {"book": "1 Corinthians", "chapters": "9"}], "theme": "For Such a Time & Paul's Rights"},
    {"day": 143, "readings": [{"book": "Esther", "chapters": "7-10"}, {"book": "1 Corinthians", "chapters": "10"}], "theme": "Deliverance & Warnings"},
    {"day": 144, "readings": [{"book": "Job", "chapters": "1-3"}, {"book": "1 Corinthians", "chapters": "11"}], "theme": "Job's Testing & Lord's Supper"},
    {"day": 145, "readings": [{"book": "Job", "chapters": "4-6"}, {"book": "1 Corinthians", "chapters": "12"}], "theme": "Eliphaz & Spiritual Gifts"},
    {"day": 146, "readings": [{"book": "Job", "chapters": "7-9"}, {"book": "1 Corinthians", "chapters": "13"}], "theme": "Job Speaks & Love"},
    {"day": 147, "readings": [{"book": "Job", "chapters": "10-12"}, {"book": "1 Corinthians", "chapters": "14"}], "theme": "Dialogue & Orderly Worship"},
    {"day": 148, "readings": [{"book": "Job", "chapters": "13-15"}, {"book": "1 Corinthians", "chapters": "15"}], "theme": "Job Defends & Resurrection"},
    {"day": 149, "readings": [{"book": "Job", "chapters": "16-18"}, {"book": "1 Corinthians", "chapters": "16"}], "theme": "Bildad & Collection"},
    {"day": 150, "readings": [{"book": "Job", "chapters": "19-21"}, {"book": "2 Corinthians", "chapters": "1"}], "theme": "Redeemer Lives & Comfort"},
    {"day": 151, "readings": [{"book": "Job", "chapters": "22-24"}, {"book": "2 Corinthians", "chapters": "2"}], "theme": "Eliphaz Again & Forgiveness"},
    
    # June
    {"day": 152, "readings": [{"book": "Job", "chapters": "25-27"}, {"book": "2 Corinthians", "chapters": "3"}], "theme": "Bildad & Glory"},
    {"day": 153, "readings": [{"book": "Job", "chapters": "28-30"}, {"book": "2 Corinthians", "chapters": "4"}], "theme": "Wisdom & Treasure in Jars"},
    {"day": 154, "readings": [{"book": "Job", "chapters": "31-33"}, {"book": "2 Corinthians", "chapters": "5"}], "theme": "Elihu & New Creation"},
    {"day": 155, "readings": [{"book": "Job", "chapters": "34-36"}, {"book": "2 Corinthians", "chapters": "6"}], "theme": "Elihu Continues & Unequal Yoke"},
    {"day": 156, "readings": [{"book": "Job", "chapters": "37-39"}, {"book": "2 Corinthians", "chapters": "7"}], "theme": "God Speaks & Godly Sorrow"},
    {"day": 157, "readings": [{"book": "Job", "chapters": "40-42"}, {"book": "2 Corinthians", "chapters": "8"}], "theme": "Job Restored & Generosity"},
    {"day": 158, "readings": [{"book": "Psalms", "chapters": "1-6"}, {"book": "2 Corinthians", "chapters": "9"}], "theme": "Blessed & Cheerful Giver"},
    {"day": 159, "readings": [{"book": "Psalms", "chapters": "7-12"}, {"book": "2 Corinthians", "chapters": "10"}], "theme": "Refuge & Spiritual Warfare"},
    {"day": 160, "readings": [{"book": "Psalms", "chapters": "13-18"}, {"book": "2 Corinthians", "chapters": "11"}], "theme": "How Long & Paul's Sufferings"},
    {"day": 161, "readings": [{"book": "Psalms", "chapters": "19-24"}, {"book": "2 Corinthians", "chapters": "12"}], "theme": "Heavens Declare & Thorn"},
    {"day": 162, "readings": [{"book": "Psalms", "chapters": "25-30"}, {"book": "2 Corinthians", "chapters": "13"}], "theme": "Lead Me & Final Greetings"},
    {"day": 163, "readings": [{"book": "Psalms", "chapters": "31-36"}, {"book": "Galatians", "chapters": "1"}], "theme": "Refuge & No Other Gospel"},
    {"day": 164, "readings": [{"book": "Psalms", "chapters": "37-42"}, {"book": "Galatians", "chapters": "2"}], "theme": "Trust & Justified by Faith"},
    {"day": 165, "readings": [{"book": "Psalms", "chapters": "43-48"}, {"book": "Galatians", "chapters": "3"}], "theme": "Why Downcast & Sons of God"},
    {"day": 166, "readings": [{"book": "Psalms", "chapters": "49-54"}, {"book": "Galatians", "chapters": "4"}], "theme": "Riches & Children of Promise"},
    {"day": 167, "readings": [{"book": "Psalms", "chapters": "55-60"}, {"book": "Galatians", "chapters": "5"}], "theme": "Cast Your Burden & Freedom"},
    {"day": 168, "readings": [{"book": "Psalms", "chapters": "61-66"}, {"book": "Galatians", "chapters": "6"}], "theme": "Hear My Cry & Sowing and Reaping"},
    {"day": 169, "readings": [{"book": "Psalms", "chapters": "67-72"}, {"book": "Ephesians", "chapters": "1"}], "theme": "Bless Us & Spiritual Blessings"},
    {"day": 170, "readings": [{"book": "Psalms", "chapters": "73-78"}, {"book": "Ephesians", "chapters": "2"}], "theme": "God's Goodness & Grace"},
    {"day": 171, "readings": [{"book": "Psalms", "chapters": "79-84"}, {"book": "Ephesians", "chapters": "3"}], "theme": "How Lovely & Mystery"},
    {"day": 172, "readings": [{"book": "Psalms", "chapters": "85-90"}, {"book": "Ephesians", "chapters": "4"}], "theme": "Dwelling Place & Unity"},
    {"day": 173, "readings": [{"book": "Psalms", "chapters": "91-96"}, {"book": "Ephesians", "chapters": "5"}], "theme": "Shelter & Walk in Love"},
    {"day": 174, "readings": [{"book": "Psalms", "chapters": "97-102"}, {"book": "Ephesians", "chapters": "6"}], "theme": "The Lord Reigns & Armor of God"},
    {"day": 175, "readings": [{"book": "Psalms", "chapters": "103-106"}, {"book": "Philippians", "chapters": "1"}], "theme": "Bless the Lord & To Live is Christ"},
    {"day": 176, "readings": [{"book": "Psalms", "chapters": "107-112"}, {"book": "Philippians", "chapters": "2"}], "theme": "Give Thanks & Humility"},
    {"day": 177, "readings": [{"book": "Psalms", "chapters": "113-118"}, {"book": "Philippians", "chapters": "3"}], "theme": "Hallel & Press On"},
    {"day": 178, "readings": [{"book": "Psalms", "chapters": "119:1-88"}, {"book": "Philippians", "chapters": "4"}], "theme": "Word & Rejoice"},
    {"day": 179, "readings": [{"book": "Psalms", "chapters": "119:89-176"}, {"book": "Colossians", "chapters": "1"}], "theme": "Word Continued & Christ Supreme"},
    {"day": 180, "readings": [{"book": "Psalms", "chapters": "120-126"}, {"book": "Colossians", "chapters": "2"}], "theme": "Songs of Ascent & Fullness in Christ"},
    {"day": 181, "readings": [{"book": "Psalms", "chapters": "127-134"}, {"book": "Colossians", "chapters": "3"}], "theme": "Pilgrim Songs & New Self"},
    {"day": 182, "readings": [{"book": "Psalms", "chapters": "135-140"}, {"book": "Colossians", "chapters": "4"}], "theme": "Praise & Final Instructions"},
    
    # July
    {"day": 183, "readings": [{"book": "Psalms", "chapters": "141-150"}, {"book": "1 Thessalonians", "chapters": "1"}], "theme": "Final Praises & Faith"},
    {"day": 184, "readings": [{"book": "Proverbs", "chapters": "1-3"}, {"book": "1 Thessalonians", "chapters": "2"}], "theme": "Wisdom Calls & Paul's Ministry"},
    {"day": 185, "readings": [{"book": "Proverbs", "chapters": "4-6"}, {"book": "1 Thessalonians", "chapters": "3"}], "theme": "Guard Your Heart & Timothy's Report"},
    {"day": 186, "readings": [{"book": "Proverbs", "chapters": "7-9"}, {"book": "1 Thessalonians", "chapters": "4"}], "theme": "Wisdom's House & Holy Living"},
    {"day": 187, "readings": [{"book": "Proverbs", "chapters": "10-12"}, {"book": "1 Thessalonians", "chapters": "5"}], "theme": "Proverbs of Solomon & Day of Lord"},
    {"day": 188, "readings": [{"book": "Proverbs", "chapters": "13-15"}, {"book": "2 Thessalonians", "chapters": "1"}], "theme": "More Proverbs & Encouragement"},
    {"day": 189, "readings": [{"book": "Proverbs", "chapters": "16-18"}, {"book": "2 Thessalonians", "chapters": "2"}], "theme": "Plans & Man of Lawlessness"},
    {"day": 190, "readings": [{"book": "Proverbs", "chapters": "19-21"}, {"book": "2 Thessalonians", "chapters": "3"}], "theme": "Fear of Lord & Idle"},
    {"day": 191, "readings": [{"book": "Proverbs", "chapters": "22-24"}, {"book": "1 Timothy", "chapters": "1"}], "theme": "Sayings of Wise & Sound Doctrine"},
    {"day": 192, "readings": [{"book": "Proverbs", "chapters": "25-27"}, {"book": "1 Timothy", "chapters": "2"}], "theme": "Hezekiah's Proverbs & Prayer"},
    {"day": 193, "readings": [{"book": "Proverbs", "chapters": "28-31"}, {"book": "1 Timothy", "chapters": "3"}], "theme": "Noble Wife & Church Leaders"},
    {"day": 194, "readings": [{"book": "Ecclesiastes", "chapters": "1-4"}, {"book": "1 Timothy", "chapters": "4"}], "theme": "Meaningless & Godliness"},
    {"day": 195, "readings": [{"book": "Ecclesiastes", "chapters": "5-8"}, {"book": "1 Timothy", "chapters": "5"}], "theme": "Fear God & Widows and Elders"},
    {"day": 196, "readings": [{"book": "Ecclesiastes", "chapters": "9-12"}, {"book": "1 Timothy", "chapters": "6"}], "theme": "Remember Creator & Contentment"},
    {"day": 197, "readings": [{"book": "Song of Solomon", "chapters": "1-4"}, {"book": "2 Timothy", "chapters": "1"}], "theme": "Love Song & Fan the Flame"},
    {"day": 198, "readings": [{"book": "Song of Solomon", "chapters": "5-8"}, {"book": "2 Timothy", "chapters": "2"}], "theme": "Beloved & Approved Worker"},
    {"day": 199, "readings": [{"book": "Isaiah", "chapters": "1-3"}, {"book": "2 Timothy", "chapters": "3"}], "theme": "Vision & Last Days"},
    {"day": 200, "readings": [{"book": "Isaiah", "chapters": "4-6"}, {"book": "2 Timothy", "chapters": "4"}], "theme": "Holy, Holy, Holy & Final Charge"},
    {"day": 201, "readings": [{"book": "Isaiah", "chapters": "7-9"}, {"book": "Titus", "chapters": "1"}], "theme": "Immanuel & Elders"},
    {"day": 202, "readings": [{"book": "Isaiah", "chapters": "10-12"}, {"book": "Titus", "chapters": "2"}], "theme": "Remnant & Sound Doctrine"},
    {"day": 203, "readings": [{"book": "Isaiah", "chapters": "13-15"}, {"book": "Titus", "chapters": "3"}], "theme": "Oracles & Good Works"},
    {"day": 204, "readings": [{"book": "Isaiah", "chapters": "16-18"}, {"book": "Philemon", "chapters": "1"}], "theme": "Nations & Onesimus"},
    {"day": 205, "readings": [{"book": "Isaiah", "chapters": "19-21"}, {"book": "Hebrews", "chapters": "1"}], "theme": "Egypt & Son Greater Than Angels"},
    {"day": 206, "readings": [{"book": "Isaiah", "chapters": "22-24"}, {"book": "Hebrews", "chapters": "2"}], "theme": "Judgment & Jesus Made Lower"},
    {"day": 207, "readings": [{"book": "Isaiah", "chapters": "25-27"}, {"book": "Hebrews", "chapters": "3"}], "theme": "Salvation & Moses"},
    {"day": 208, "readings": [{"book": "Isaiah", "chapters": "28-30"}, {"book": "Hebrews", "chapters": "4"}], "theme": "Woe & Sabbath Rest"},
    {"day": 209, "readings": [{"book": "Isaiah", "chapters": "31-33"}, {"book": "Hebrews", "chapters": "5"}], "theme": "Trust God & High Priest"},
    {"day": 210, "readings": [{"book": "Isaiah", "chapters": "34-36"}, {"book": "Hebrews", "chapters": "6"}], "theme": "Judgment & Maturity"},
    {"day": 211, "readings": [{"book": "Isaiah", "chapters": "37-39"}, {"book": "Hebrews", "chapters": "7"}], "theme": "Hezekiah & Melchizedek"},
    {"day": 212, "readings": [{"book": "Isaiah", "chapters": "40-42"}, {"book": "Hebrews", "chapters": "8"}], "theme": "Comfort & New Covenant"},
    {"day": 213, "readings": [{"book": "Isaiah", "chapters": "43-45"}, {"book": "Hebrews", "chapters": "9"}], "theme": "I Am & Better Sacrifice"},
    
    # August
    {"day": 214, "readings": [{"book": "Isaiah", "chapters": "46-48"}, {"book": "Hebrews", "chapters": "10"}], "theme": "No Other God & Draw Near"},
    {"day": 215, "readings": [{"book": "Isaiah", "chapters": "49-51"}, {"book": "Hebrews", "chapters": "11"}], "theme": "Servant & Faith Heroes"},
    {"day": 216, "readings": [{"book": "Isaiah", "chapters": "52-54"}, {"book": "Hebrews", "chapters": "12"}], "theme": "Suffering Servant & Discipline"},
    {"day": 217, "readings": [{"book": "Isaiah", "chapters": "55-57"}, {"book": "Hebrews", "chapters": "13"}], "theme": "Seek the Lord & Final Words"},
    {"day": 218, "readings": [{"book": "Isaiah", "chapters": "58-60"}, {"book": "James", "chapters": "1"}], "theme": "True Fasting & Trials"},
    {"day": 219, "readings": [{"book": "Isaiah", "chapters": "61-63"}, {"book": "James", "chapters": "2"}], "theme": "Year of Favor & Faith and Works"},
    {"day": 220, "readings": [{"book": "Isaiah", "chapters": "64-66"}, {"book": "James", "chapters": "3"}], "theme": "New Heavens & Tongue"},
    {"day": 221, "readings": [{"book": "Jeremiah", "chapters": "1-3"}, {"book": "James", "chapters": "4"}], "theme": "Called & Submit to God"},
    {"day": 222, "readings": [{"book": "Jeremiah", "chapters": "4-6"}, {"book": "James", "chapters": "5"}], "theme": "Disaster & Patience"},
    {"day": 223, "readings": [{"book": "Jeremiah", "chapters": "7-9"}, {"book": "1 Peter", "chapters": "1"}], "theme": "Temple & Living Hope"},
    {"day": 224, "readings": [{"book": "Jeremiah", "chapters": "10-12"}, {"book": "1 Peter", "chapters": "2"}], "theme": "Idols & Living Stones"},
    {"day": 225, "readings": [{"book": "Jeremiah", "chapters": "13-15"}, {"book": "1 Peter", "chapters": "3"}], "theme": "Linen Belt & Suffering"},
    {"day": 226, "readings": [{"book": "Jeremiah", "chapters": "16-18"}, {"book": "1 Peter", "chapters": "4"}], "theme": "Potter & Suffering for Christ"},
    {"day": 227, "readings": [{"book": "Jeremiah", "chapters": "19-21"}, {"book": "1 Peter", "chapters": "5"}], "theme": "Broken Jar & Elders"},
    {"day": 228, "readings": [{"book": "Jeremiah", "chapters": "22-24"}, {"book": "2 Peter", "chapters": "1"}], "theme": "Kings & Make Calling Sure"},
    {"day": 229, "readings": [{"book": "Jeremiah", "chapters": "25-27"}, {"book": "2 Peter", "chapters": "2"}], "theme": "70 Years & False Teachers"},
    {"day": 230, "readings": [{"book": "Jeremiah", "chapters": "28-30"}, {"book": "2 Peter", "chapters": "3"}], "theme": "False Prophets & Day of Lord"},
    {"day": 231, "readings": [{"book": "Jeremiah", "chapters": "31-33"}, {"book": "1 John", "chapters": "1"}], "theme": "New Covenant & Light"},
    {"day": 232, "readings": [{"book": "Jeremiah", "chapters": "34-36"}, {"book": "1 John", "chapters": "2"}], "theme": "Scroll & Antichrist"},
    {"day": 233, "readings": [{"book": "Jeremiah", "chapters": "37-39"}, {"book": "1 John", "chapters": "3"}], "theme": "Jerusalem Falls & Children of God"},
    {"day": 234, "readings": [{"book": "Jeremiah", "chapters": "40-42"}, {"book": "1 John", "chapters": "4"}], "theme": "Gedaliah & Test Spirits"},
    {"day": 235, "readings": [{"book": "Jeremiah", "chapters": "43-45"}, {"book": "1 John", "chapters": "5"}], "theme": "Egypt & Eternal Life"},
    {"day": 236, "readings": [{"book": "Jeremiah", "chapters": "46-48"}, {"book": "2 John", "chapters": "1"}], "theme": "Nations & Truth and Love"},
    {"day": 237, "readings": [{"book": "Jeremiah", "chapters": "49-52"}, {"book": "3 John", "chapters": "1"}], "theme": "More Nations & Hospitality"},
    {"day": 238, "readings": [{"book": "Lamentations", "chapters": "1-2"}, {"book": "Jude", "chapters": "1"}], "theme": "Lament & Contend for Faith"},
    {"day": 239, "readings": [{"book": "Lamentations", "chapters": "3-5"}, {"book": "Revelation", "chapters": "1"}], "theme": "Hope & Vision of Christ"},
    {"day": 240, "readings": [{"book": "Ezekiel", "chapters": "1-3"}, {"book": "Revelation", "chapters": "2"}], "theme": "Vision & Seven Churches"},
    {"day": 241, "readings": [{"book": "Ezekiel", "chapters": "4-6"}, {"book": "Revelation", "chapters": "3"}], "theme": "Siege & More Churches"},
    {"day": 242, "readings": [{"book": "Ezekiel", "chapters": "7-9"}, {"book": "Revelation", "chapters": "4"}], "theme": "End & Throne Room"},
    {"day": 243, "readings": [{"book": "Ezekiel", "chapters": "10-12"}, {"book": "Revelation", "chapters": "5"}], "theme": "Glory Departs & The Scroll"},
    {"day": 244, "readings": [{"book": "Ezekiel", "chapters": "13-15"}, {"book": "Revelation", "chapters": "6"}], "theme": "False Prophets & Six Seals"},
    
    # September
    {"day": 245, "readings": [{"book": "Ezekiel", "chapters": "16-18"}, {"book": "Revelation", "chapters": "7"}], "theme": "Jerusalem's Sin & 144,000"},
    {"day": 246, "readings": [{"book": "Ezekiel", "chapters": "19-21"}, {"book": "Revelation", "chapters": "8"}], "theme": "Lament & Seventh Seal"},
    {"day": 247, "readings": [{"book": "Ezekiel", "chapters": "22-24"}, {"book": "Revelation", "chapters": "9"}], "theme": "Sins of Jerusalem & Trumpets"},
    {"day": 248, "readings": [{"book": "Ezekiel", "chapters": "25-27"}, {"book": "Revelation", "chapters": "10"}], "theme": "Nations & Little Scroll"},
    {"day": 249, "readings": [{"book": "Ezekiel", "chapters": "28-30"}, {"book": "Revelation", "chapters": "11"}], "theme": "Tyre & Two Witnesses"},
    {"day": 250, "readings": [{"book": "Ezekiel", "chapters": "31-33"}, {"book": "Revelation", "chapters": "12"}], "theme": "Egypt & Woman and Dragon"},
    {"day": 251, "readings": [{"book": "Ezekiel", "chapters": "34-36"}, {"book": "Revelation", "chapters": "13"}], "theme": "Shepherds & Two Beasts"},
    {"day": 252, "readings": [{"book": "Ezekiel", "chapters": "37-39"}, {"book": "Revelation", "chapters": "14"}], "theme": "Dry Bones & Lamb and 144,000"},
    {"day": 253, "readings": [{"book": "Ezekiel", "chapters": "40-42"}, {"book": "Revelation", "chapters": "15"}], "theme": "New Temple & Seven Angels"},
    {"day": 254, "readings": [{"book": "Ezekiel", "chapters": "43-45"}, {"book": "Revelation", "chapters": "16"}], "theme": "Glory Returns & Seven Bowls"},
    {"day": 255, "readings": [{"book": "Ezekiel", "chapters": "46-48"}, {"book": "Revelation", "chapters": "17"}], "theme": "River & Babylon"},
    {"day": 256, "readings": [{"book": "Daniel", "chapters": "1-3"}, {"book": "Revelation", "chapters": "18"}], "theme": "Fiery Furnace & Babylon Falls"},
    {"day": 257, "readings": [{"book": "Daniel", "chapters": "4-6"}, {"book": "Revelation", "chapters": "19"}], "theme": "Lions' Den & Hallelujah"},
    {"day": 258, "readings": [{"book": "Daniel", "chapters": "7-9"}, {"book": "Revelation", "chapters": "20"}], "theme": "Visions & Millennium"},
    {"day": 259, "readings": [{"book": "Daniel", "chapters": "10-12"}, {"book": "Revelation", "chapters": "21"}], "theme": "End Times & New Jerusalem"},
    {"day": 260, "readings": [{"book": "Hosea", "chapters": "1-4"}, {"book": "Revelation", "chapters": "22"}], "theme": "Unfaithful Wife & Come Lord Jesus"},
    {"day": 261, "readings": [{"book": "Hosea", "chapters": "5-8"}, {"book": "Psalms", "chapters": "1-2"}], "theme": "Israel's Sin & Blessed"},
    {"day": 262, "readings": [{"book": "Hosea", "chapters": "9-11"}, {"book": "Psalms", "chapters": "3-4"}], "theme": "Punishment & Help"},
    {"day": 263, "readings": [{"book": "Hosea", "chapters": "12-14"}, {"book": "Psalms", "chapters": "5-6"}], "theme": "Repentance & Morning Prayer"},
    {"day": 264, "readings": [{"book": "Joel", "chapters": "1-3"}, {"book": "Psalms", "chapters": "7-8"}], "theme": "Day of Lord & Glory of God"},
    {"day": 265, "readings": [{"book": "Amos", "chapters": "1-3"}, {"book": "Psalms", "chapters": "9-10"}], "theme": "Judgment & Wicked"},
    {"day": 266, "readings": [{"book": "Amos", "chapters": "4-6"}, {"book": "Psalms", "chapters": "11-12"}], "theme": "Prepare to Meet God & Help Lord"},
    {"day": 267, "readings": [{"book": "Amos", "chapters": "7-9"}, {"book": "Psalms", "chapters": "13-14"}], "theme": "Visions & Fool"},
    {"day": 268, "readings": [{"book": "Obadiah", "chapters": "1"}, {"book": "Psalms", "chapters": "15-16"}], "theme": "Edom & Who May Dwell"},
    {"day": 269, "readings": [{"book": "Jonah", "chapters": "1-4"}, {"book": "Psalms", "chapters": "17-18"}], "theme": "Great Fish & Rock"},
    {"day": 270, "readings": [{"book": "Micah", "chapters": "1-3"}, {"book": "Psalms", "chapters": "19-20"}], "theme": "Judgment & Heavens Declare"},
    {"day": 271, "readings": [{"book": "Micah", "chapters": "4-5"}, {"book": "Psalms", "chapters": "21-22"}], "theme": "Ruler from Bethlehem & My God Why"},
    {"day": 272, "readings": [{"book": "Micah", "chapters": "6-7"}, {"book": "Psalms", "chapters": "23-24"}], "theme": "What Lord Requires & Shepherd"},
    {"day": 273, "readings": [{"book": "Nahum", "chapters": "1-3"}, {"book": "Psalms", "chapters": "25-26"}], "theme": "Nineveh & Lead Me"},
    {"day": 274, "readings": [{"book": "Habakkuk", "chapters": "1-3"}, {"book": "Psalms", "chapters": "27-28"}], "theme": "Why Lord & Light"},
    
    # October
    {"day": 275, "readings": [{"book": "Zephaniah", "chapters": "1-3"}, {"book": "Psalms", "chapters": "29-30"}], "theme": "Day of Lord & Ascribe Glory"},
    {"day": 276, "readings": [{"book": "Haggai", "chapters": "1-2"}, {"book": "Psalms", "chapters": "31-32"}], "theme": "Build Temple & Refuge"},
    {"day": 277, "readings": [{"book": "Zechariah", "chapters": "1-3"}, {"book": "Psalms", "chapters": "33-34"}], "theme": "Visions & Taste and See"},
    {"day": 278, "readings": [{"book": "Zechariah", "chapters": "4-6"}, {"book": "Psalms", "chapters": "35-36"}], "theme": "Lampstand & Contend Lord"},
    {"day": 279, "readings": [{"book": "Zechariah", "chapters": "7-9"}, {"book": "Psalms", "chapters": "37-38"}], "theme": "Fasting & Do Not Fret"},
    {"day": 280, "readings": [{"book": "Zechariah", "chapters": "10-12"}, {"book": "Psalms", "chapters": "39-40"}], "theme": "Shepherd Struck & New Song"},
    {"day": 281, "readings": [{"book": "Zechariah", "chapters": "13-14"}, {"book": "Psalms", "chapters": "41-42"}], "theme": "Day of Lord & As Deer Pants"},
    {"day": 282, "readings": [{"book": "Malachi", "chapters": "1-2"}, {"book": "Psalms", "chapters": "43-44"}], "theme": "Love & Send Light"},
    {"day": 283, "readings": [{"book": "Malachi", "chapters": "3-4"}, {"book": "Psalms", "chapters": "45-46"}], "theme": "Messenger & God Our Refuge"},
    {"day": 284, "readings": [{"book": "Matthew", "chapters": "1-2"}, {"book": "Psalms", "chapters": "47-48"}], "theme": "Jesus' Birth & Great King"},
    {"day": 285, "readings": [{"book": "Matthew", "chapters": "3-4"}, {"book": "Psalms", "chapters": "49-50"}], "theme": "Baptism & Hear O Earth"},
    {"day": 286, "readings": [{"book": "Matthew", "chapters": "5-6"}, {"book": "Psalms", "chapters": "51-52"}], "theme": "Sermon on Mount & Create Clean Heart"},
    {"day": 287, "readings": [{"book": "Matthew", "chapters": "7-8"}, {"book": "Psalms", "chapters": "53-54"}], "theme": "Do Not Judge & Save Me"},
    {"day": 288, "readings": [{"book": "Matthew", "chapters": "9-10"}, {"book": "Psalms", "chapters": "55-56"}], "theme": "Workers & Cast Burden"},
    {"day": 289, "readings": [{"book": "Matthew", "chapters": "11-12"}, {"book": "Psalms", "chapters": "57-58"}], "theme": "Rest & Be Merciful"},
    {"day": 290, "readings": [{"book": "Matthew", "chapters": "13-14"}, {"book": "Psalms", "chapters": "59-60"}], "theme": "Parables & Deliver Me"},
    {"day": 291, "readings": [{"book": "Matthew", "chapters": "15-16"}, {"book": "Psalms", "chapters": "61-62"}], "theme": "Peter's Confession & Hear My Cry"},
    {"day": 292, "readings": [{"book": "Matthew", "chapters": "17-18"}, {"book": "Psalms", "chapters": "63-64"}], "theme": "Transfiguration & Earnestly Seek"},
    {"day": 293, "readings": [{"book": "Matthew", "chapters": "19-20"}, {"book": "Psalms", "chapters": "65-66"}], "theme": "Rich Young Man & Praise"},
    {"day": 294, "readings": [{"book": "Matthew", "chapters": "21-22"}, {"book": "Psalms", "chapters": "67-68"}], "theme": "Triumphal Entry & Bless Us"},
    {"day": 295, "readings": [{"book": "Matthew", "chapters": "23-24"}, {"book": "Psalms", "chapters": "69-70"}], "theme": "Woes & Save Me"},
    {"day": 296, "readings": [{"book": "Matthew", "chapters": "25-26"}, {"book": "Psalms", "chapters": "71-72"}], "theme": "Parables & Refuge"},
    {"day": 297, "readings": [{"book": "Matthew", "chapters": "27-28"}, {"book": "Psalms", "chapters": "73-74"}], "theme": "Crucifixion & Sanctuary"},
    {"day": 298, "readings": [{"book": "Mark", "chapters": "1-2"}, {"book": "Psalms", "chapters": "75-76"}], "theme": "Good News & We Give Thanks"},
    {"day": 299, "readings": [{"book": "Mark", "chapters": "3-4"}, {"book": "Psalms", "chapters": "77-78"}], "theme": "Parables & I Cry Aloud"},
    {"day": 300, "readings": [{"book": "Mark", "chapters": "5-6"}, {"book": "Psalms", "chapters": "79-80"}], "theme": "Miracles & Restore Us"},
    {"day": 301, "readings": [{"book": "Mark", "chapters": "7-8"}, {"book": "Psalms", "chapters": "81-82"}], "theme": "Tradition & Sing for Joy"},
    {"day": 302, "readings": [{"book": "Mark", "chapters": "9-10"}, {"book": "Psalms", "chapters": "83-84"}], "theme": "Children & How Lovely"},
    {"day": 303, "readings": [{"book": "Mark", "chapters": "11-12"}, {"book": "Psalms", "chapters": "85-86"}], "theme": "Temple & Hear Me"},
    {"day": 304, "readings": [{"book": "Mark", "chapters": "13-14"}, {"book": "Psalms", "chapters": "87-88"}], "theme": "End Times & Cry Day and Night"},
    {"day": 305, "readings": [{"book": "Mark", "chapters": "15-16"}, {"book": "Psalms", "chapters": "89-90"}], "theme": "Death and Resurrection & Faithfulness"},
    
    # November
    {"day": 306, "readings": [{"book": "Luke", "chapters": "1-2"}, {"book": "Psalms", "chapters": "91-92"}], "theme": "Birth Narratives & Dwelling Place"},
    {"day": 307, "readings": [{"book": "Luke", "chapters": "3-4"}, {"book": "Psalms", "chapters": "93-94"}], "theme": "Ministry Begins & The Lord Reigns"},
    {"day": 308, "readings": [{"book": "Luke", "chapters": "5-6"}, {"book": "Psalms", "chapters": "95-96"}], "theme": "Calling & Sing a New Song"},
    {"day": 309, "readings": [{"book": "Luke", "chapters": "7-8"}, {"book": "Psalms", "chapters": "97-98"}], "theme": "Faith & The Lord Reigns"},
    {"day": 310, "readings": [{"book": "Luke", "chapters": "9-10"}, {"book": "Psalms", "chapters": "99-100"}], "theme": "Mission & Shout for Joy"},
    {"day": 311, "readings": [{"book": "Luke", "chapters": "11-12"}, {"book": "Psalms", "chapters": "101-102"}], "theme": "Teaching & Prayer of Afflicted"},
    {"day": 312, "readings": [{"book": "Luke", "chapters": "13-14"}, {"book": "Psalms", "chapters": "103-104"}], "theme": "Repentance & Bless the Lord"},
    {"day": 313, "readings": [{"book": "Luke", "chapters": "15-16"}, {"book": "Psalms", "chapters": "105-106"}], "theme": "Lost & Give Thanks"},
    {"day": 314, "readings": [{"book": "Luke", "chapters": "17-18"}, {"book": "Psalms", "chapters": "107-108"}], "theme": "Faith & Give Thanks to Lord"},
    {"day": 315, "readings": [{"book": "Luke", "chapters": "19-20"}, {"book": "Psalms", "chapters": "109-110"}], "theme": "Jerusalem & Help Me"},
    {"day": 316, "readings": [{"book": "Luke", "chapters": "21-22"}, {"book": "Psalms", "chapters": "111-112"}], "theme": "Signs & Praise the Lord"},
    {"day": 317, "readings": [{"book": "Luke", "chapters": "23-24"}, {"book": "Psalms", "chapters": "113-114"}], "theme": "Cross and Resurrection & Praise"},
    {"day": 318, "readings": [{"book": "John", "chapters": "1-2"}, {"book": "Psalms", "chapters": "115-116"}], "theme": "The Word & Love the Lord"},
    {"day": 319, "readings": [{"book": "John", "chapters": "3-4"}, {"book": "Psalms", "chapters": "117-118"}], "theme": "Born Again & Give Thanks"},
    {"day": 320, "readings": [{"book": "John", "chapters": "5-6"}, {"book": "Psalms", "chapters": "119:1-48"}], "theme": "Signs & Blessed"},
    {"day": 321, "readings": [{"book": "John", "chapters": "7-8"}, {"book": "Psalms", "chapters": "119:49-104"}], "theme": "Feast & Your Word"},
    {"day": 322, "readings": [{"book": "John", "chapters": "9-10"}, {"book": "Psalms", "chapters": "119:105-176"}], "theme": "Good Shepherd & Lamp"},
    {"day": 323, "readings": [{"book": "John", "chapters": "11-12"}, {"book": "Psalms", "chapters": "120-122"}], "theme": "Lazarus & Look to Mountains"},
    {"day": 324, "readings": [{"book": "John", "chapters": "13-14"}, {"book": "Psalms", "chapters": "123-125"}], "theme": "Upper Room & Eyes to Lord"},
    {"day": 325, "readings": [{"book": "John", "chapters": "15-16"}, {"book": "Psalms", "chapters": "126-128"}], "theme": "Vine & Restored"},
    {"day": 326, "readings": [{"book": "John", "chapters": "17-18"}, {"book": "Psalms", "chapters": "129-131"}], "theme": "Prayer & Hope in Lord"},
    {"day": 327, "readings": [{"book": "John", "chapters": "19-21"}, {"book": "Psalms", "chapters": "132-134"}], "theme": "Crucifixion & Bless the Lord"},
    {"day": 328, "readings": [{"book": "Acts", "chapters": "1-2"}, {"book": "Psalms", "chapters": "135-136"}], "theme": "Pentecost & Give Thanks"},
    {"day": 329, "readings": [{"book": "Acts", "chapters": "3-4"}, {"book": "Psalms", "chapters": "137-138"}], "theme": "Boldness & By Rivers"},
    {"day": 330, "readings": [{"book": "Acts", "chapters": "5-6"}, {"book": "Psalms", "chapters": "139-140"}], "theme": "Ananias & You Search Me"},
    {"day": 331, "readings": [{"book": "Acts", "chapters": "7-8"}, {"book": "Psalms", "chapters": "141-142"}], "theme": "Stephen & Set Guard"},
    {"day": 332, "readings": [{"book": "Acts", "chapters": "9-10"}, {"book": "Psalms", "chapters": "143-144"}], "theme": "Conversion & Spirit Willing"},
    {"day": 333, "readings": [{"book": "Acts", "chapters": "11-12"}, {"book": "Psalms", "chapters": "145-146"}], "theme": "Gentiles & Praise"},
    {"day": 334, "readings": [{"book": "Acts", "chapters": "13-14"}, {"book": "Psalms", "chapters": "147-148"}], "theme": "First Journey & Praise the Lord"},
    {"day": 335, "readings": [{"book": "Acts", "chapters": "15-16"}, {"book": "Psalms", "chapters": "149-150"}], "theme": "Council & Let Everything Praise"},
    
    # December
    {"day": 336, "readings": [{"book": "Acts", "chapters": "17-18"}, {"book": "Proverbs", "chapters": "1-2"}], "theme": "Athens & Wisdom"},
    {"day": 337, "readings": [{"book": "Acts", "chapters": "19-20"}, {"book": "Proverbs", "chapters": "3-4"}], "theme": "Ephesus & Trust in Lord"},
    {"day": 338, "readings": [{"book": "Acts", "chapters": "21-22"}, {"book": "Proverbs", "chapters": "5-6"}], "theme": "Arrest & Warning"},
    {"day": 339, "readings": [{"book": "Acts", "chapters": "23-24"}, {"book": "Proverbs", "chapters": "7-8"}], "theme": "Trial & Wisdom Calls"},
    {"day": 340, "readings": [{"book": "Acts", "chapters": "25-26"}, {"book": "Proverbs", "chapters": "9-10"}], "theme": "Appeal & Two Ways"},
    {"day": 341, "readings": [{"book": "Acts", "chapters": "27-28"}, {"book": "Proverbs", "chapters": "11-12"}], "theme": "Rome & Righteous"},
    {"day": 342, "readings": [{"book": "Romans", "chapters": "1-2"}, {"book": "Proverbs", "chapters": "13-14"}], "theme": "Gospel & Wisdom"},
    {"day": 343, "readings": [{"book": "Romans", "chapters": "3-4"}, {"book": "Proverbs", "chapters": "15-16"}], "theme": "Justification & Gentle Answer"},
    {"day": 344, "readings": [{"book": "Romans", "chapters": "5-6"}, {"book": "Proverbs", "chapters": "17-18"}], "theme": "Peace & Name of Lord"},
    {"day": 345, "readings": [{"book": "Romans", "chapters": "7-8"}, {"book": "Proverbs", "chapters": "19-20"}], "theme": "Spirit & Fear of Lord"},
    {"day": 346, "readings": [{"book": "Romans", "chapters": "9-10"}, {"book": "Proverbs", "chapters": "21-22"}], "theme": "Israel & Train Child"},
    {"day": 347, "readings": [{"book": "Romans", "chapters": "11-12"}, {"book": "Proverbs", "chapters": "23-24"}], "theme": "Mercy & Listen to Father"},
    {"day": 348, "readings": [{"book": "Romans", "chapters": "13-14"}, {"book": "Proverbs", "chapters": "25-26"}], "theme": "Authorities & Apples of Gold"},
    {"day": 349, "readings": [{"book": "Romans", "chapters": "15-16"}, {"book": "Proverbs", "chapters": "27-28"}], "theme": "Hope & Faithful Wounds"},
    {"day": 350, "readings": [{"book": "1 Corinthians", "chapters": "1-2"}, {"book": "Proverbs", "chapters": "29-30"}], "theme": "Cross & Open Rebuke"},
    {"day": 351, "readings": [{"book": "1 Corinthians", "chapters": "3-4"}, {"book": "Proverbs", "chapters": "31"}], "theme": "Foundation & Noble Wife"},
    {"day": 352, "readings": [{"book": "1 Corinthians", "chapters": "5-6"}, {"book": "Ecclesiastes", "chapters": "1-2"}], "theme": "Body Temple & Vanity"},
    {"day": 353, "readings": [{"book": "1 Corinthians", "chapters": "7-8"}, {"book": "Ecclesiastes", "chapters": "3-4"}], "theme": "Marriage & Time for Everything"},
    {"day": 354, "readings": [{"book": "1 Corinthians", "chapters": "9-10"}, {"book": "Ecclesiastes", "chapters": "5-6"}], "theme": "Freedom & Fear God"},
    {"day": 355, "readings": [{"book": "1 Corinthians", "chapters": "11-12"}, {"book": "Ecclesiastes", "chapters": "7-8"}], "theme": "Gifts & Wisdom"},
    {"day": 356, "readings": [{"book": "1 Corinthians", "chapters": "13-14"}, {"book": "Ecclesiastes", "chapters": "9-10"}], "theme": "Love & Enjoy Life"},
    {"day": 357, "readings": [{"book": "1 Corinthians", "chapters": "15-16"}, {"book": "Ecclesiastes", "chapters": "11-12"}], "theme": "Resurrection & Remember Creator"},
    {"day": 358, "readings": [{"book": "2 Corinthians", "chapters": "1-3"}, {"book": "Song of Solomon", "chapters": "1-2"}], "theme": "Comfort & Beloved"},
    {"day": 359, "readings": [{"book": "2 Corinthians", "chapters": "4-6"}, {"book": "Song of Solomon", "chapters": "3-4"}], "theme": "Treasure & Beautiful"},
    {"day": 360, "readings": [{"book": "2 Corinthians", "chapters": "7-9"}, {"book": "Song of Solomon", "chapters": "5-6"}], "theme": "Giving & My Beloved"},
    {"day": 361, "readings": [{"book": "2 Corinthians", "chapters": "10-13"}, {"book": "Song of Solomon", "chapters": "7-8"}], "theme": "Weakness & Love Strong"},
    {"day": 362, "readings": [{"book": "Galatians", "chapters": "1-3"}, {"book": "Isaiah", "chapters": "1-2"}], "theme": "No Other Gospel & Come Let Us Reason"},
    {"day": 363, "readings": [{"book": "Galatians", "chapters": "4-6"}, {"book": "Isaiah", "chapters": "3-4"}], "theme": "Freedom & Branch of Lord"},
    {"day": 364, "readings": [{"book": "Ephesians", "chapters": "1-3"}, {"book": "Isaiah", "chapters": "5-6"}], "theme": "Blessings & Holy Holy Holy"},
    {"day": 365, "readings": [{"book": "Ephesians", "chapters": "4-6"}, {"book": "Isaiah", "chapters": "7-9"}], "theme": "Unity and Armor & Immanuel"},
]

def get_reading_plan():
    return BIBLE_IN_A_YEAR_PLAN

def get_today_reading():
    from datetime import datetime, timezone
    day_of_year = datetime.now(timezone.utc).timetuple().tm_yday
    index = (day_of_year - 1) % len(BIBLE_IN_A_YEAR_PLAN)
    return BIBLE_IN_A_YEAR_PLAN[index]

def get_reading_by_day(day: int):
    if 1 <= day <= len(BIBLE_IN_A_YEAR_PLAN):
        return BIBLE_IN_A_YEAR_PLAN[day - 1]
    return None
